### ISSUE TITLE
由於違反ToS 協議，帳戶已被封禁

### ISSUE THREAD

**Issue by lhie1** [steveny5997/learning#1]
https://github.com/steveny5997/learning/blob/47db67e63bc2ad41f55a823c8f8b19b808f436aa/Dler%20Cloud.yaml

**Comment by steveny5997** [comment]
> https://github.com/steveny5997/learning/blob/47db67e63bc2ad41f55a823c8f8b19b808f436aa/Dler%20Cloud.yaml

Deleted. Sorry for my mistake.
